---
title: Dr. Urologista
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
menu: item
permalink: ":categories/:title/"
baseurl: "/"
